/**
 ******************************************************************************
 * @file           : Bai1_ToChucBNXN.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CFGR_REG_OFFSET	0x08UL
#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define GPIOA_BASE_ADDR	0x40020000UL

int main(void)
{
			uint32_t *pRccCfgrReg =  (uint32_t *) RCC_CFGR_REG_ADDR;
			*pRccCfgrReg &= ~(0x3 << 21);
			*pRccCfgrReg |= ( 1 << 25);
			*pRccCfgrReg |= ( 1 << 26);
			uint32_t *pRccAhb1Enr = (uint32_t *)(RCC_CFGR_REG_ADDR + 0x3);
			*pRccAhb1Enr |= ( 1 << 0);
			uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
			*pGPIOAModeReg &= ~( 0x3 << 16);
			*pGPIOAModeReg |= ( 0x2 << 16);
			uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
			*pGPIOAAltFunHighReg &= ~( 0xf << 0);
    /* Loop forever */
	for(;;);
}
